apiVersion: v1
kind: Service
metadata:
  labels:
    name: rhoas-quarkus-kafka-quickstart
    version: 1.0-SNAPSHOT
  name: rhoas-quarkus-kafka-quickstart
spec:
  selector:
    name: rhoas-quarkus-kafka-quickstart
    version: 1.0-SNAPSHOT
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110